/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SegurancaRouteImport } from './routes/seguranca'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as MovimentoRouteImport } from './routes/movimento'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as EmbaixadoresRouteImport } from './routes/embaixadores'
import { Route as DiretrizesRouteImport } from './routes/diretrizes'
import { Route as DescobrirStatusRouteImport } from './routes/descobrir-status'
import { Route as DescobrirRouteImport } from './routes/descobrir'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConhecerPessoasRouteImport } from './routes/conhecer-pessoas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LiveIndexRouteImport } from './routes/live.index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as SStatusIdRouteImport } from './routes/s.$statusId'
import { Route as PPostIdRouteImport } from './routes/p.$postId'
import { Route as MeetRoomIdRouteImport } from './routes/meet.$roomId'
import { Route as LiveNewRouteImport } from './routes/live.new'
import { Route as LiveLiveIdRouteImport } from './routes/live.$liveId'
import { Route as InviteInviterIdRouteImport } from './routes/invite.$inviterId'
import { Route as GGroupIdRouteImport } from './routes/g.$groupId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedRecordingsRouteImport } from './routes/_authenticated/recordings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMeusConvitesRouteImport } from './routes/_authenticated/meus-convites'
import { Route as AuthenticatedHashtagsRouteImport } from './routes/_authenticated/hashtags'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicSupportRouteImport } from './routes/api/public/support'
import { Route as ApiPublicStatusPushRouteImport } from './routes/api/public/status-push'
import { Route as ApiPublicPostPushRouteImport } from './routes/api/public/post-push'
import { Route as AuthenticatedHashtagTagRouteImport } from './routes/_authenticated/hashtag.$tag'
import { Route as AuthenticatedChatConversationIdRouteImport } from './routes/_authenticated/chat.$conversationId'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsRefundSweeperRouteImport } from './routes/api/public/payments/refund-sweeper'
import { Route as ApiPublicHooksUnreadMessageEmailsRouteImport } from './routes/api/public/hooks/unread-message-emails'
import { Route as ApiPublicHooksSchedulerTickRouteImport } from './routes/api/public/hooks/scheduler-tick'
import { Route as ApiPublicHooksLivekitEgressRouteImport } from './routes/api/public/hooks/livekit-egress'
import { Route as ApiPublicCallsStatusRouteImport } from './routes/api/public/calls/status'
import { Route as ApiPublicAuthCheckSignupIpRouteImport } from './routes/api/public/auth/check-signup-ip'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SegurancaRoute = SegurancaRouteImport.update({
  id: '/seguranca',
  path: '/seguranca',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const MovimentoRoute = MovimentoRouteImport.update({
  id: '/movimento',
  path: '/movimento',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbaixadoresRoute = EmbaixadoresRouteImport.update({
  id: '/embaixadores',
  path: '/embaixadores',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretrizesRoute = DiretrizesRouteImport.update({
  id: '/diretrizes',
  path: '/diretrizes',
  getParentRoute: () => rootRouteImport,
} as any)
const DescobrirStatusRoute = DescobrirStatusRouteImport.update({
  id: '/descobrir-status',
  path: '/descobrir-status',
  getParentRoute: () => rootRouteImport,
} as any)
const DescobrirRoute = DescobrirRouteImport.update({
  id: '/descobrir',
  path: '/descobrir',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConhecerPessoasRoute = ConhecerPessoasRouteImport.update({
  id: '/conhecer-pessoas',
  path: '/conhecer-pessoas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveIndexRoute = LiveIndexRouteImport.update({
  id: '/live/',
  path: '/live/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const SStatusIdRoute = SStatusIdRouteImport.update({
  id: '/s/$statusId',
  path: '/s/$statusId',
  getParentRoute: () => rootRouteImport,
} as any)
const PPostIdRoute = PPostIdRouteImport.update({
  id: '/p/$postId',
  path: '/p/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoomIdRoute = MeetRoomIdRouteImport.update({
  id: '/meet/$roomId',
  path: '/meet/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveNewRoute = LiveNewRouteImport.update({
  id: '/live/new',
  path: '/live/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveLiveIdRoute = LiveLiveIdRouteImport.update({
  id: '/live/$liveId',
  path: '/live/$liveId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteInviterIdRoute = InviteInviterIdRouteImport.update({
  id: '/invite/$inviterId',
  path: '/invite/$inviterId',
  getParentRoute: () => rootRouteImport,
} as any)
const GGroupIdRoute = GGroupIdRouteImport.update({
  id: '/g/$groupId',
  path: '/g/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecordingsRoute = AuthenticatedRecordingsRouteImport.update({
  id: '/recordings',
  path: '/recordings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeusConvitesRoute =
  AuthenticatedMeusConvitesRouteImport.update({
    id: '/meus-convites',
    path: '/meus-convites',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHashtagsRoute = AuthenticatedHashtagsRouteImport.update({
  id: '/hashtags',
  path: '/hashtags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSupportRoute = ApiPublicSupportRouteImport.update({
  id: '/api/public/support',
  path: '/api/public/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStatusPushRoute = ApiPublicStatusPushRouteImport.update({
  id: '/api/public/status-push',
  path: '/api/public/status-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPostPushRoute = ApiPublicPostPushRouteImport.update({
  id: '/api/public/post-push',
  path: '/api/public/post-push',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHashtagTagRoute = AuthenticatedHashtagTagRouteImport.update({
  id: '/hashtag/$tag',
  path: '/hashtag/$tag',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatConversationIdRoute =
  AuthenticatedChatConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedChatRoute,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsRefundSweeperRoute =
  ApiPublicPaymentsRefundSweeperRouteImport.update({
    id: '/api/public/payments/refund-sweeper',
    path: '/api/public/payments/refund-sweeper',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksUnreadMessageEmailsRoute =
  ApiPublicHooksUnreadMessageEmailsRouteImport.update({
    id: '/api/public/hooks/unread-message-emails',
    path: '/api/public/hooks/unread-message-emails',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSchedulerTickRoute =
  ApiPublicHooksSchedulerTickRouteImport.update({
    id: '/api/public/hooks/scheduler-tick',
    path: '/api/public/hooks/scheduler-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLivekitEgressRoute =
  ApiPublicHooksLivekitEgressRouteImport.update({
    id: '/api/public/hooks/livekit-egress',
    path: '/api/public/hooks/livekit-egress',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCallsStatusRoute = ApiPublicCallsStatusRouteImport.update({
  id: '/api/public/calls/status',
  path: '/api/public/calls/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthCheckSignupIpRoute =
  ApiPublicAuthCheckSignupIpRouteImport.update({
    id: '/api/public/auth/check-signup-ip',
    path: '/api/public/auth/check-signup-ip',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conhecer-pessoas': typeof ConhecerPessoasRoute
  '/contact': typeof ContactRoute
  '/descobrir': typeof DescobrirRoute
  '/descobrir-status': typeof DescobrirStatusRoute
  '/diretrizes': typeof DiretrizesRoute
  '/embaixadores': typeof EmbaixadoresRoute
  '/guide': typeof GuideRoute
  '/movimento': typeof MovimentoRoute
  '/posts': typeof PostsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/meus-convites': typeof AuthenticatedMeusConvitesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recordings': typeof AuthenticatedRecordingsRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/invite/$inviterId': typeof InviteInviterIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/live/new': typeof LiveNewRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/s/$statusId': typeof SStatusIdRoute
  '/u/$username': typeof UUsernameRoute
  '/live/': typeof LiveIndexRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/api/public/post-push': typeof ApiPublicPostPushRoute
  '/api/public/status-push': typeof ApiPublicStatusPushRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/auth/check-signup-ip': typeof ApiPublicAuthCheckSignupIpRoute
  '/api/public/calls/status': typeof ApiPublicCallsStatusRoute
  '/api/public/hooks/livekit-egress': typeof ApiPublicHooksLivekitEgressRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
  '/api/public/hooks/unread-message-emails': typeof ApiPublicHooksUnreadMessageEmailsRoute
  '/api/public/payments/refund-sweeper': typeof ApiPublicPaymentsRefundSweeperRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conhecer-pessoas': typeof ConhecerPessoasRoute
  '/contact': typeof ContactRoute
  '/descobrir': typeof DescobrirRoute
  '/descobrir-status': typeof DescobrirStatusRoute
  '/diretrizes': typeof DiretrizesRoute
  '/embaixadores': typeof EmbaixadoresRoute
  '/guide': typeof GuideRoute
  '/movimento': typeof MovimentoRoute
  '/posts': typeof PostsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/chat': typeof AuthenticatedChatRouteWithChildren
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/meus-convites': typeof AuthenticatedMeusConvitesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/recordings': typeof AuthenticatedRecordingsRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/invite/$inviterId': typeof InviteInviterIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/live/new': typeof LiveNewRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/s/$statusId': typeof SStatusIdRoute
  '/u/$username': typeof UUsernameRoute
  '/live': typeof LiveIndexRoute
  '/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/api/public/post-push': typeof ApiPublicPostPushRoute
  '/api/public/status-push': typeof ApiPublicStatusPushRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/auth/check-signup-ip': typeof ApiPublicAuthCheckSignupIpRoute
  '/api/public/calls/status': typeof ApiPublicCallsStatusRoute
  '/api/public/hooks/livekit-egress': typeof ApiPublicHooksLivekitEgressRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
  '/api/public/hooks/unread-message-emails': typeof ApiPublicHooksUnreadMessageEmailsRoute
  '/api/public/payments/refund-sweeper': typeof ApiPublicPaymentsRefundSweeperRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/conhecer-pessoas': typeof ConhecerPessoasRoute
  '/contact': typeof ContactRoute
  '/descobrir': typeof DescobrirRoute
  '/descobrir-status': typeof DescobrirStatusRoute
  '/diretrizes': typeof DiretrizesRoute
  '/embaixadores': typeof EmbaixadoresRoute
  '/guide': typeof GuideRoute
  '/movimento': typeof MovimentoRoute
  '/posts': typeof PostsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/seguranca': typeof SegurancaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/chat': typeof AuthenticatedChatRouteWithChildren
  '/_authenticated/hashtags': typeof AuthenticatedHashtagsRoute
  '/_authenticated/meus-convites': typeof AuthenticatedMeusConvitesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/recordings': typeof AuthenticatedRecordingsRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/g/$groupId': typeof GGroupIdRoute
  '/invite/$inviterId': typeof InviteInviterIdRoute
  '/live/$liveId': typeof LiveLiveIdRoute
  '/live/new': typeof LiveNewRoute
  '/meet/$roomId': typeof MeetRoomIdRoute
  '/p/$postId': typeof PPostIdRoute
  '/s/$statusId': typeof SStatusIdRoute
  '/u/$username': typeof UUsernameRoute
  '/live/': typeof LiveIndexRoute
  '/_authenticated/chat/$conversationId': typeof AuthenticatedChatConversationIdRoute
  '/_authenticated/hashtag/$tag': typeof AuthenticatedHashtagTagRoute
  '/api/public/post-push': typeof ApiPublicPostPushRoute
  '/api/public/status-push': typeof ApiPublicStatusPushRoute
  '/api/public/support': typeof ApiPublicSupportRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/auth/check-signup-ip': typeof ApiPublicAuthCheckSignupIpRoute
  '/api/public/calls/status': typeof ApiPublicCallsStatusRoute
  '/api/public/hooks/livekit-egress': typeof ApiPublicHooksLivekitEgressRoute
  '/api/public/hooks/scheduler-tick': typeof ApiPublicHooksSchedulerTickRoute
  '/api/public/hooks/unread-message-emails': typeof ApiPublicHooksUnreadMessageEmailsRoute
  '/api/public/payments/refund-sweeper': typeof ApiPublicPaymentsRefundSweeperRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/conhecer-pessoas'
    | '/contact'
    | '/descobrir'
    | '/descobrir-status'
    | '/diretrizes'
    | '/embaixadores'
    | '/guide'
    | '/movimento'
    | '/posts'
    | '/privacy'
    | '/reset-password'
    | '/seguranca'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/chat'
    | '/hashtags'
    | '/meus-convites'
    | '/profile'
    | '/recordings'
    | '/scheduled'
    | '/email/unsubscribe'
    | '/g/$groupId'
    | '/invite/$inviterId'
    | '/live/$liveId'
    | '/live/new'
    | '/meet/$roomId'
    | '/p/$postId'
    | '/s/$statusId'
    | '/u/$username'
    | '/live/'
    | '/chat/$conversationId'
    | '/hashtag/$tag'
    | '/api/public/post-push'
    | '/api/public/status-push'
    | '/api/public/support'
    | '/lovable/email/suppression'
    | '/api/public/auth/check-signup-ip'
    | '/api/public/calls/status'
    | '/api/public/hooks/livekit-egress'
    | '/api/public/hooks/scheduler-tick'
    | '/api/public/hooks/unread-message-emails'
    | '/api/public/payments/refund-sweeper'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/conhecer-pessoas'
    | '/contact'
    | '/descobrir'
    | '/descobrir-status'
    | '/diretrizes'
    | '/embaixadores'
    | '/guide'
    | '/movimento'
    | '/posts'
    | '/privacy'
    | '/reset-password'
    | '/seguranca'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/chat'
    | '/hashtags'
    | '/meus-convites'
    | '/profile'
    | '/recordings'
    | '/scheduled'
    | '/email/unsubscribe'
    | '/g/$groupId'
    | '/invite/$inviterId'
    | '/live/$liveId'
    | '/live/new'
    | '/meet/$roomId'
    | '/p/$postId'
    | '/s/$statusId'
    | '/u/$username'
    | '/live'
    | '/chat/$conversationId'
    | '/hashtag/$tag'
    | '/api/public/post-push'
    | '/api/public/status-push'
    | '/api/public/support'
    | '/lovable/email/suppression'
    | '/api/public/auth/check-signup-ip'
    | '/api/public/calls/status'
    | '/api/public/hooks/livekit-egress'
    | '/api/public/hooks/scheduler-tick'
    | '/api/public/hooks/unread-message-emails'
    | '/api/public/payments/refund-sweeper'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/admin'
    | '/auth'
    | '/conhecer-pessoas'
    | '/contact'
    | '/descobrir'
    | '/descobrir-status'
    | '/diretrizes'
    | '/embaixadores'
    | '/guide'
    | '/movimento'
    | '/posts'
    | '/privacy'
    | '/reset-password'
    | '/seguranca'
    | '/sitemap.xml'
    | '/support'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/chat'
    | '/_authenticated/hashtags'
    | '/_authenticated/meus-convites'
    | '/_authenticated/profile'
    | '/_authenticated/recordings'
    | '/_authenticated/scheduled'
    | '/email/unsubscribe'
    | '/g/$groupId'
    | '/invite/$inviterId'
    | '/live/$liveId'
    | '/live/new'
    | '/meet/$roomId'
    | '/p/$postId'
    | '/s/$statusId'
    | '/u/$username'
    | '/live/'
    | '/_authenticated/chat/$conversationId'
    | '/_authenticated/hashtag/$tag'
    | '/api/public/post-push'
    | '/api/public/status-push'
    | '/api/public/support'
    | '/lovable/email/suppression'
    | '/api/public/auth/check-signup-ip'
    | '/api/public/calls/status'
    | '/api/public/hooks/livekit-egress'
    | '/api/public/hooks/scheduler-tick'
    | '/api/public/hooks/unread-message-emails'
    | '/api/public/payments/refund-sweeper'
    | '/api/public/payments/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ConhecerPessoasRoute: typeof ConhecerPessoasRoute
  ContactRoute: typeof ContactRoute
  DescobrirRoute: typeof DescobrirRoute
  DescobrirStatusRoute: typeof DescobrirStatusRoute
  DiretrizesRoute: typeof DiretrizesRoute
  EmbaixadoresRoute: typeof EmbaixadoresRoute
  GuideRoute: typeof GuideRoute
  MovimentoRoute: typeof MovimentoRoute
  PostsRoute: typeof PostsRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SegurancaRoute: typeof SegurancaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  GGroupIdRoute: typeof GGroupIdRoute
  InviteInviterIdRoute: typeof InviteInviterIdRoute
  LiveLiveIdRoute: typeof LiveLiveIdRoute
  LiveNewRoute: typeof LiveNewRoute
  MeetRoomIdRoute: typeof MeetRoomIdRoute
  PPostIdRoute: typeof PPostIdRoute
  SStatusIdRoute: typeof SStatusIdRoute
  UUsernameRoute: typeof UUsernameRoute
  LiveIndexRoute: typeof LiveIndexRoute
  ApiPublicPostPushRoute: typeof ApiPublicPostPushRoute
  ApiPublicStatusPushRoute: typeof ApiPublicStatusPushRoute
  ApiPublicSupportRoute: typeof ApiPublicSupportRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicAuthCheckSignupIpRoute: typeof ApiPublicAuthCheckSignupIpRoute
  ApiPublicCallsStatusRoute: typeof ApiPublicCallsStatusRoute
  ApiPublicHooksLivekitEgressRoute: typeof ApiPublicHooksLivekitEgressRoute
  ApiPublicHooksSchedulerTickRoute: typeof ApiPublicHooksSchedulerTickRoute
  ApiPublicHooksUnreadMessageEmailsRoute: typeof ApiPublicHooksUnreadMessageEmailsRoute
  ApiPublicPaymentsRefundSweeperRoute: typeof ApiPublicPaymentsRefundSweeperRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seguranca': {
      id: '/seguranca'
      path: '/seguranca'
      fullPath: '/seguranca'
      preLoaderRoute: typeof SegurancaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movimento': {
      id: '/movimento'
      path: '/movimento'
      fullPath: '/movimento'
      preLoaderRoute: typeof MovimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embaixadores': {
      id: '/embaixadores'
      path: '/embaixadores'
      fullPath: '/embaixadores'
      preLoaderRoute: typeof EmbaixadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretrizes': {
      id: '/diretrizes'
      path: '/diretrizes'
      fullPath: '/diretrizes'
      preLoaderRoute: typeof DiretrizesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descobrir-status': {
      id: '/descobrir-status'
      path: '/descobrir-status'
      fullPath: '/descobrir-status'
      preLoaderRoute: typeof DescobrirStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/descobrir': {
      id: '/descobrir'
      path: '/descobrir'
      fullPath: '/descobrir'
      preLoaderRoute: typeof DescobrirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conhecer-pessoas': {
      id: '/conhecer-pessoas'
      path: '/conhecer-pessoas'
      fullPath: '/conhecer-pessoas'
      preLoaderRoute: typeof ConhecerPessoasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/': {
      id: '/live/'
      path: '/live'
      fullPath: '/live/'
      preLoaderRoute: typeof LiveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$statusId': {
      id: '/s/$statusId'
      path: '/s/$statusId'
      fullPath: '/s/$statusId'
      preLoaderRoute: typeof SStatusIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$postId': {
      id: '/p/$postId'
      path: '/p/$postId'
      fullPath: '/p/$postId'
      preLoaderRoute: typeof PPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$roomId': {
      id: '/meet/$roomId'
      path: '/meet/$roomId'
      fullPath: '/meet/$roomId'
      preLoaderRoute: typeof MeetRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/new': {
      id: '/live/new'
      path: '/live/new'
      fullPath: '/live/new'
      preLoaderRoute: typeof LiveNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/$liveId': {
      id: '/live/$liveId'
      path: '/live/$liveId'
      fullPath: '/live/$liveId'
      preLoaderRoute: typeof LiveLiveIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$inviterId': {
      id: '/invite/$inviterId'
      path: '/invite/$inviterId'
      fullPath: '/invite/$inviterId'
      preLoaderRoute: typeof InviteInviterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$groupId': {
      id: '/g/$groupId'
      path: '/g/$groupId'
      fullPath: '/g/$groupId'
      preLoaderRoute: typeof GGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recordings': {
      id: '/_authenticated/recordings'
      path: '/recordings'
      fullPath: '/recordings'
      preLoaderRoute: typeof AuthenticatedRecordingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meus-convites': {
      id: '/_authenticated/meus-convites'
      path: '/meus-convites'
      fullPath: '/meus-convites'
      preLoaderRoute: typeof AuthenticatedMeusConvitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hashtags': {
      id: '/_authenticated/hashtags'
      path: '/hashtags'
      fullPath: '/hashtags'
      preLoaderRoute: typeof AuthenticatedHashtagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/support': {
      id: '/api/public/support'
      path: '/api/public/support'
      fullPath: '/api/public/support'
      preLoaderRoute: typeof ApiPublicSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/status-push': {
      id: '/api/public/status-push'
      path: '/api/public/status-push'
      fullPath: '/api/public/status-push'
      preLoaderRoute: typeof ApiPublicStatusPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-push': {
      id: '/api/public/post-push'
      path: '/api/public/post-push'
      fullPath: '/api/public/post-push'
      preLoaderRoute: typeof ApiPublicPostPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/hashtag/$tag': {
      id: '/_authenticated/hashtag/$tag'
      path: '/hashtag/$tag'
      fullPath: '/hashtag/$tag'
      preLoaderRoute: typeof AuthenticatedHashtagTagRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/$conversationId': {
      id: '/_authenticated/chat/$conversationId'
      path: '/$conversationId'
      fullPath: '/chat/$conversationId'
      preLoaderRoute: typeof AuthenticatedChatConversationIdRouteImport
      parentRoute: typeof AuthenticatedChatRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/refund-sweeper': {
      id: '/api/public/payments/refund-sweeper'
      path: '/api/public/payments/refund-sweeper'
      fullPath: '/api/public/payments/refund-sweeper'
      preLoaderRoute: typeof ApiPublicPaymentsRefundSweeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/unread-message-emails': {
      id: '/api/public/hooks/unread-message-emails'
      path: '/api/public/hooks/unread-message-emails'
      fullPath: '/api/public/hooks/unread-message-emails'
      preLoaderRoute: typeof ApiPublicHooksUnreadMessageEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/scheduler-tick': {
      id: '/api/public/hooks/scheduler-tick'
      path: '/api/public/hooks/scheduler-tick'
      fullPath: '/api/public/hooks/scheduler-tick'
      preLoaderRoute: typeof ApiPublicHooksSchedulerTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/livekit-egress': {
      id: '/api/public/hooks/livekit-egress'
      path: '/api/public/hooks/livekit-egress'
      fullPath: '/api/public/hooks/livekit-egress'
      preLoaderRoute: typeof ApiPublicHooksLivekitEgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/calls/status': {
      id: '/api/public/calls/status'
      path: '/api/public/calls/status'
      fullPath: '/api/public/calls/status'
      preLoaderRoute: typeof ApiPublicCallsStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth/check-signup-ip': {
      id: '/api/public/auth/check-signup-ip'
      path: '/api/public/auth/check-signup-ip'
      fullPath: '/api/public/auth/check-signup-ip'
      preLoaderRoute: typeof ApiPublicAuthCheckSignupIpRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedChatRouteChildren {
  AuthenticatedChatConversationIdRoute: typeof AuthenticatedChatConversationIdRoute
}

const AuthenticatedChatRouteChildren: AuthenticatedChatRouteChildren = {
  AuthenticatedChatConversationIdRoute: AuthenticatedChatConversationIdRoute,
}

const AuthenticatedChatRouteWithChildren =
  AuthenticatedChatRoute._addFileChildren(AuthenticatedChatRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedChatRoute: typeof AuthenticatedChatRouteWithChildren
  AuthenticatedHashtagsRoute: typeof AuthenticatedHashtagsRoute
  AuthenticatedMeusConvitesRoute: typeof AuthenticatedMeusConvitesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRecordingsRoute: typeof AuthenticatedRecordingsRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedHashtagTagRoute: typeof AuthenticatedHashtagTagRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChatRoute: AuthenticatedChatRouteWithChildren,
  AuthenticatedHashtagsRoute: AuthenticatedHashtagsRoute,
  AuthenticatedMeusConvitesRoute: AuthenticatedMeusConvitesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRecordingsRoute: AuthenticatedRecordingsRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedHashtagTagRoute: AuthenticatedHashtagTagRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ConhecerPessoasRoute: ConhecerPessoasRoute,
  ContactRoute: ContactRoute,
  DescobrirRoute: DescobrirRoute,
  DescobrirStatusRoute: DescobrirStatusRoute,
  DiretrizesRoute: DiretrizesRoute,
  EmbaixadoresRoute: EmbaixadoresRoute,
  GuideRoute: GuideRoute,
  MovimentoRoute: MovimentoRoute,
  PostsRoute: PostsRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SegurancaRoute: SegurancaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  GGroupIdRoute: GGroupIdRoute,
  InviteInviterIdRoute: InviteInviterIdRoute,
  LiveLiveIdRoute: LiveLiveIdRoute,
  LiveNewRoute: LiveNewRoute,
  MeetRoomIdRoute: MeetRoomIdRoute,
  PPostIdRoute: PPostIdRoute,
  SStatusIdRoute: SStatusIdRoute,
  UUsernameRoute: UUsernameRoute,
  LiveIndexRoute: LiveIndexRoute,
  ApiPublicPostPushRoute: ApiPublicPostPushRoute,
  ApiPublicStatusPushRoute: ApiPublicStatusPushRoute,
  ApiPublicSupportRoute: ApiPublicSupportRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicAuthCheckSignupIpRoute: ApiPublicAuthCheckSignupIpRoute,
  ApiPublicCallsStatusRoute: ApiPublicCallsStatusRoute,
  ApiPublicHooksLivekitEgressRoute: ApiPublicHooksLivekitEgressRoute,
  ApiPublicHooksSchedulerTickRoute: ApiPublicHooksSchedulerTickRoute,
  ApiPublicHooksUnreadMessageEmailsRoute:
    ApiPublicHooksUnreadMessageEmailsRoute,
  ApiPublicPaymentsRefundSweeperRoute: ApiPublicPaymentsRefundSweeperRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
